---
version: '3'
services:
  netbox:
    build:
      context: ../
      dockerfile: development/Dockerfile
    image: "ntc-netbox-plugin-app-metrics/netbox:${NETBOX_VER}-py${PYTHON_VER}"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./dev.env
    volumes:
      - ./base_configuration.py:/opt/netbox/netbox/netbox/base_configuration.py
      - ./netbox_${NETBOX_VER}/configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ../netbox_app_metrics:/source/netbox_app_metrics
    tty: true
  worker:
    build:
      context: ../
      dockerfile: development/Dockerfile
    image: "ntc-netbox-plugin-app-metrics/netbox:${NETBOX_VER}-py${PYTHON_VER}"
    command: sh -c "python manage.py rqworker"
    depends_on:
      - netbox
    env_file:
      - ./dev.env
    volumes:
      - ./base_configuration.py:/opt/netbox/netbox/netbox/base_configuration.py
      - ./netbox_${NETBOX_VER}/configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ../netbox_app_metrics:/source/netbox_app_metrics
    tty: true
  postgres:
    image: postgres:10
    env_file: dev.env
    volumes:
      - pgdata_netbox_app_metrics:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine
    command:
      - sh
      - -c  # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD  ## $$ because of docker-compose
    env_file: ./dev.env
volumes:
  pgdata_netbox_app_metrics:
